---

- name: update web servers
  hosts: web

  tasks: 
  - name: Ensure Git is Installed
    yum: 
      name: git
      state: installed

  - name: Ensure Essence code is updated
    git: 
      repo: https://github.com/ravi2krishna/ecomm.git
      dest: /var/www/html

...

