---

- name: update web servers
  hosts: n2

  tasks: 
  - name: Ensure Git is Installed
    yum: 
      name: git
      state: installed

  - name: Ensure Food code is updated
    git: 
      repo: https://github.com/ravi2krishna/food.git
      dest: /var/www/html

...

